packages:
  - '.'

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
