# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Auto Version Increment

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  auto-version:
    runs-on: ubuntu-latest
    # Only run if the PR doesn't already have a version bump
    if: |
      !contains(github.event.pull_request.title, 'version bump') &&
      !contains(github.event.pull_request.title, 'bump version') &&
      !contains(github.event.pull_request.title, 'chore: bump') &&
      !contains(github.event.pull_request.title, 'release')
    
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.2.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get current version
        id: current-version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check if version was recently bumped
        id: version-check
        run: |
          # Check if the last commit was already a version bump
          last_commit_msg=$(git log -1 --pretty=format:"%s")
          if [[ "$last_commit_msg" == *"chore: bump version"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Version was already bumped in the last commit: $last_commit_msg"
          else
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "No recent version bump found, proceeding with increment"
          fi

      - name: Increment patch version
        if: steps.version-check.outputs.skip == 'false'
        run: pnpm --no-git-tag-version version patch

      - name: Get new version
        if: steps.version-check.outputs.skip == 'false'
        id: new-version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Configure Git
        if: steps.version-check.outputs.skip == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit version bump
        if: steps.version-check.outputs.skip == 'false'
        run: |
          git add package.json
          git commit -m "chore: bump version from ${{ steps.current-version.outputs.version }} to ${{ steps.new-version.outputs.version }}"
          git push

      - name: Update dev branch with version bump
        if: steps.version-check.outputs.skip == 'false'
        run: |
          # Fetch the latest dev branch
          git fetch origin dev
          # Create a temporary branch from dev
          git checkout -b temp-version-update origin/dev
          # Cherry-pick the version bump commit
          git cherry-pick HEAD~1
          # Push the changes to dev
          git push origin temp-version-update:dev
          # Switch back to the original branch
          git checkout ${{ github.head_ref }}
          # Clean up the temporary branch
          git branch -D temp-version-update

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const wasSkipped = '${{ steps.version-check.outputs.skip }}' === 'true';
            const body = wasSkipped 
              ? `ℹ️ **Version Bump Skipped**\n\nVersion bump was skipped because the last commit already contains a version bump.`
              : `🚀 **Auto Version Bump**\n\nVersion automatically incremented from \`${{ steps.current-version.outputs.version }}\` to \`${{ steps.new-version.outputs.version }}\` for deployment to main branch.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
