export interface FeatureTourSlide {
  id: string;
  title: string;
  text: string;
  alt: string;
}

export type FeatureTourImageSize = 'desktop' | 'mobile';

/**
 * Screenshots are generated by `pnpm screenshots:feature-tour`
 * (e2e/feature-tour/feature-tour.capture.ts), which writes
 * `{id}-desktop.png` and `{id}-mobile.png` for each slide id below.
 */
export const featureTourImagePath = (
  slide: FeatureTourSlide,
  size: FeatureTourImageSize
): string => `/assets/images/feature-tour/${slide.id}-${size}.png`;

export const FEATURE_TOUR_SLIDES: readonly FeatureTourSlide[] = [
  {
    id: 'proportional',
    title: 'Split tax and tip fairly',
    text: "Enter what each person ordered, and PipSplit splits the tax and tip in proportion to each person's share. Anything left over, like a shared appetizer, is divided evenly, so nobody pays tip on someone else's steak.",
    alt: 'Split summary showing each person’s own amount, their share of a shared appetizer, and their proportional share of tax and tip',
  },
  {
    id: 'split-methods',
    title: 'Amounts, percentages, or shares',
    text: 'Every expense can use the split method that fits: exact amounts, percentages, or shares for ratios like 2:1. PipSplit shows each person’s effective percentage as you type.',
    alt: 'Expense split by shares, with each member’s effective percentage shown next to their share',
  },
  {
    id: 'receipt-scan',
    title: 'Scan a receipt',
    text: 'Snap a photo of a receipt and PipSplit pulls out the total and each line item. Assign items to the people who ordered them, and the split is done for you.',
    alt: 'Scanned receipt with line items assigned to group members',
  },
  {
    id: 'vacation-rental',
    title: 'Split a vacation rental by the night',
    text: 'Not everyone stayed every night? Mark who was there on the occupancy grid and PipSplit works out a fair share for each person.',
    alt: 'Vacation rental occupancy grid showing which members stayed on each night',
  },
  {
    id: 'settle-up',
    title: 'Settle up in the fewest payments',
    text: 'See who owes whom at a glance. PipSplit calculates the fewest transfers needed to settle the whole group, and you can send payment requests or mark everything paid in one step.',
    alt: 'Group summary with a fewest-transfers settlement table',
  },
  {
    id: 'and-more',
    title: 'And much more',
    text: 'Memorize recurring bills like rent and utilities for quick entry, organize expenses with categories, and keep a full history of every payment. All free, for as many groups as you need.',
    alt: 'List of memorized recurring expenses',
  },
];
